In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [182]:
#Load Dataset
df = pd.read_csv("house_prices.csv")

In [183]:
df.sample(5)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
160999,160999,4 BHK Ready to Occupy Flat for sale Pari Chowk,NaN,4.50 Cr,10227.0,greater-noida,NaN,Ready to Move,Ground out of 12,Resale,...,NaN,NaN,NaN,4,NaN,NaN,NaN,4400 sqft,NaN,NaN
159551,159551,3 BHK Ready to Occupy Flat for sale in Aldeia ...,This beautiful 3 BHK Flat is available for sal...,5.50 Cr,18333.0,goa,NaN,Ready to Move,2 out of 2,Resale,...,NaN,"Garden/Park, Pool",Aldeia De Goa,3,4,1 Open,Freehold,3000 sqft,NaN,NaN
40515,40515,2 BHK Ready to Occupy Flat for sale Shanthi Co...,This exquisite 2 BHK Flat is offered for sale ...,88 Lac,8800.0,chennai,NaN,Ready to Move,2 out of 3,Resale,...,North,Main Road,NaN,2,1,1 Covered,Freehold,1000 sqft,NaN,NaN
111121,111121,2 BHK Ready to Occupy Flat for sale Larika est...,"2 BHK, Multistorey Apartment is available for ...",16 Lac,2228.0,kolkata,NaN,Ready to Move,4 out of 4,Resale,...,NaN,NaN,NaN,2,NaN,NaN,NaN,718 sqft,NaN,NaN
147830,147830,3 BHK Ready to Occupy Flat for sale Dayal Bagh,"Dayal Bagh, Agra has an attractive 3 BHK Flat ...",55 Lac,3333.0,agra,1500 sqft,Ready to Move,1 out of 4,Resale,...,West,Main Road,NaN,2,2,1 Covered,Freehold,NaN,NaN,NaN

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [143]:
# df1 = df.drop(columns=["Dimensions" , "Plot Area"] )
df.drop(columns=["Dimensions" , "Plot Area" , "Title" , "Description"] , inplace=True)

In [144]:
df.sample(5)

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
172360,172360,50 Lac,4762.0,nagpur,NaN,Ready to Move,2 out of 5,Resale,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,1050 sqft
87174,87174,42 Lac,3000.0,jaipur,NaN,Ready to Move,3 out of 6,New Property,Unfurnished,East,"Garden/Park, Main Road",NaN,2,2,NaN,Freehold,1400 sqft
79477,79477,69 Lac,NaN,hyderabad,956 sqft,Ready to Move,5 out of 5,Resale,Furnished,East,Garden/Park,NaN,2,1,1 Covered,Freehold,NaN
11814,11814,3.65 Cr,NaN,ahmedabad,4734 sqft,Ready to Move,16 out of 16,Resale,Unfurnished,East,NaN,Adani Shantigram Waterlily,5,1,"2 Covered,",Freehold,NaN
64530,64530,1.25 Cr,8367.0,gurgaon,NaN,Ready to Move,3 out of 20,Resale,Unfurnished,East,NaN,Godrej Aria,2,2,1 Covered,NaN,1494 sqft

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Amount(in rupees)  187531 non-null  object
 2   Price (in rupees)  169866 non-null  float64
 3   location           187531 non-null  object
 4   Carpet Area        106858 non-null  object
 5   Status             186916 non-null  object
 6   Floor              180454 non-null  object
 7   Transaction        187448 non-null  object
 8   Furnishing         184634 non-null  object
 9   facing             117298 non-null  object
 10  overlooking        106095 non-null  object
 11  Society            77853 non-null   object
 12  Bathroom           186703 non-null  object
 13  Balcony            138596 non-null  object
 14  Car Parking        84174 non-null   object
 15  Ownership          122014 non-null  object
 16  Super Area         79846 non-null   object
dtypes: float64(1), int64(1), object(15)
memory usage: 24.3+ MB

In [146]:
# Clean the data
import re

def extract_number(x):
    if pd.isnull(x):
        return None
    nums = re.findall(r'\d+', str(x))
    return float(nums[0]) if nums else None

In [147]:
extract_number("9")

9.0

In [148]:
float("9")

9.0

In [149]:
df["Bathroom"] = df["Bathroom"].apply(extract_number)
df["Balcony"] = df["Balcony"].apply(extract_number)
df['Carpet Area'] = df['Carpet Area'].apply(extract_number)
df['Super Area'] = df['Super Area'].apply(extract_number)

In [150]:
df['Car_Parking_Count'] = df['Car Parking'].str.extract(r'(\d+)').astype(float)

In [151]:
df['Car_Parking_Type'] = df['Car Parking'].astype(str).str.extract(r'([A-Za-z]+)')
df['Car_Parking_Type'] = df['Car_Parking_Type'].str.lower()

In [152]:
df['Car Parking']

0                NaN
1             1 Open
2          1 Covered
3                NaN
4          1 Covered
             ...
187526     1 Covered
187527     1 Covered
187528    1 Covered,
187529           NaN
187530     1 Covered
Name: Car Parking, Length: 187531, dtype: object

In [153]:
df['Car Parking'].astype(str).str.extract(r'([A-Za-z]+)')

              0
0           nan
1          Open
2       Covered
3           nan
4       Covered
...         ...
187526  Covered
187527  Covered
187528  Covered
187529      nan
187530  Covered

[187531 rows x 1 columns]

In [154]:
df.sample()

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Car_Parking_Count,Car_Parking_Type
103877,103877,3.95 Cr,NaN,kolkata,2550.0,Ready to Move,2 out of 4,Resale,Semi-Furnished,East,Garden/Park,Sunny Park,3.0,2.0,2 Covered,Freehold,NaN,2.0,covered

In [155]:
df.drop(columns=["Car Parking" , "Floor"] ,  inplace=True)

In [156]:
df.sample(5)

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,Car_Parking_Count,Car_Parking_Type
171795,171795,2.40 Cr,9678.0,mohali,1890.0,Ready to Move,New Property,Semi-Furnished,South - East,"Garden/Park, Pool",JLPL Falcon View,3.0,3.0,Freehold,NaN,1.0,covered
178309,178309,1.10 Cr,5405.0,surat,NaN,Ready to Move,New Property,Unfurnished,East,"Garden/Park, Main Road",NaN,3.0,2.0,Freehold,2035.0,NaN,nan
92788,92788,Call for Price,NaN,kolkata,NaN,Ready to Move,Resale,Unfurnished,NaN,NaN,NaN,2.0,NaN,NaN,960.0,1.0,open
171819,171819,65 Lac,3939.0,mohali,1400.0,Ready to Move,Resale,Semi-Furnished,North - East,"Garden/Park, Main Road",Nirwana Greens 4,3.0,3.0,Freehold,NaN,1.0,covered
98586,98586,22 Lac,3090.0,kolkata,NaN,Ready to Move,Resale,Semi-Furnished,NaN,NaN,NaN,2.0,1.0,NaN,712.0,NaN,nan

In [157]:
def clean_price(x):
    x = str(x).replace(',', '').replace('₹','').strip().lower()

    if 'cr' in x:
        return float(x.replace('cr','')) * 10000000
    elif 'crore' in x:
        return float(x.replace('crore','')) * 10000000
    elif 'lac' in x or 'lakh' in x:
        return float(x.replace('lac','').replace('lakh','')) * 100000
    elif "call for price" in x :
        return 0.0
    else:
        return float(x)

In [158]:
clean_price("2.92 Cr")

29200000.0

In [159]:
df["Amount(in rupees)"] = df["Amount(in rupees)"].apply(clean_price)

In [160]:
df.sample(5)

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,Car_Parking_Count,Car_Parking_Type
174799,174799,3350000.0,3100.0,raipur,950.0,Ready to Move,New Property,Unfurnished,East,"Pool, Garden/Park",NaN,2.0,2.0,Freehold,NaN,1.0,covered
150284,150284,3000000.0,3333.0,bhopal,NaN,Ready to Move,Resale,NaN,NaN,NaN,NaN,2.0,NaN,NaN,900.0,NaN,nan
70881,70881,22900000.0,9502.0,hyderabad,2410.0,Ready to Move,Resale,Semi-Furnished,West,Garden/Park,NaN,3.0,2.0,NaN,NaN,2.0,covered
122707,122707,17800000.0,12714.0,new-delhi,1300.0,Ready to Move,Resale,Semi-Furnished,NaN,Main Road,Rama Apartment,2.0,3.0,Freehold,NaN,1.0,covered
14909,14909,6100000.0,5648.0,ahmedabad,NaN,Ready to Move,Resale,Semi-Furnished,NaN,NaN,NaN,2.0,2.0,NaN,1080.0,NaN,nan

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Amount(in rupees)  187531 non-null  float64
 2   Price (in rupees)  169866 non-null  float64
 3   location           187531 non-null  object
 4   Carpet Area        106858 non-null  float64
 5   Status             186916 non-null  object
 6   Transaction        187448 non-null  object
 7   Furnishing         184634 non-null  object
 8   facing             117298 non-null  object
 9   overlooking        106095 non-null  object
 10  Society            77853 non-null   object
 11  Bathroom           186703 non-null  float64
 12  Balcony            138596 non-null  float64
 13  Ownership          122014 non-null  object
 14  Super Area         79846 non-null   float64
 15  Car_Parking_Count  84174 non-null   float64
 16  Car_Parking_Type   187531 non-null  object
dtypes: float64(7), int64(1), object(9)
memory usage: 24.3+ MB

In [162]:
# Filling Missing Values

In [163]:
num_cols = ['Carpet Area','Super Area','Bathroom','Balcony','Car_Parking_Count' ,'Price (in rupees)']

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [164]:
df.sample(5)

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,Car_Parking_Count,Car_Parking_Type
7113,7113,5230000.0,5811.0,ahmedabad,900.0,Ready to Move,Resale,Unfurnished,NaN,Main Road,Shilalekh Apartments,2.0,2.0,Freehold,1250.0,1.0,nan
168854,168854,4300000.0,3723.0,kochi,1155.0,Ready to Move,Resale,Furnished,North,"Garden/Park, Pool, Main Road",Flairalliance Atrium,2.0,2.0,Freehold,1250.0,1.0,covered
134767,134767,17800000.0,12714.0,new-delhi,1300.0,Ready to Move,Resale,Semi-Furnished,NaN,Main Road,Rama Apartment,2.0,3.0,Freehold,1250.0,1.0,covered
21566,21566,8800000.0,5254.0,bangalore,1000.0,Ready to Move,New Property,Unfurnished,North,Garden/Park,NaN,3.0,2.0,Freehold,1675.0,1.0,covered
96592,96592,22500000.0,11538.0,kolkata,1000.0,Ready to Move,Resale,Furnished,NaN,NaN,Rosedale Garden,2.0,2.0,NaN,1950.0,1.0,nan

In [165]:
cat_cols = ['location', 'Status', 'Furnishing', 'facing', 'Transaction']

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [166]:
df.sample(5)

,Index,Amount(in rupees),Price (in rupees),Carpet Area,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,...,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West,Transaction_Other,Transaction_Rent/Lease,Transaction_Resale
122611,122611,5000000.0,10000.0,1000.0,NaN,NaN,1.0,2.0,NaN,500.0,...,False,False,False,False,False,False,False,False,False,True
44203,44203,15000000.0,7150.0,1450.0,"Garden/Park, Pool, Main Road",NaN,4.0,2.0,Freehold,1250.0,...,False,True,False,False,False,False,False,False,False,False
136348,136348,5100000.0,6667.0,675.0,NaN,NaN,2.0,2.0,Freehold,1250.0,...,False,False,False,False,False,False,False,False,False,True
84740,84740,20400000.0,6034.0,2348.0,"Pool, Garden/Park, Main Road",NaN,4.0,4.0,NaN,1250.0,...,False,False,False,False,False,False,False,False,False,False
158764,158764,7960000.0,5378.0,1450.0,Garden/Park,NaN,2.0,1.0,Freehold,1250.0,...,False,True,False,False,False,False,False,False,False,False

In [167]:
df = df.astype(int, errors='ignore')

In [168]:
df

,Index,Amount(in rupees),Price (in rupees),Carpet Area,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,...,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West,Transaction_Other,Transaction_Rent/Lease,Transaction_Resale
0,0,4200000,6000,500,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,1250,...,0,0,0,0,0,0,0,0,0,1
1,1,9800000,13799,473,Garden/Park,Dosti Vihar,2,2,Freehold,1250,...,0,0,0,0,0,0,0,0,0,1
2,2,14000000,17500,779,Garden/Park,Sunrise by Kalpataru,2,2,Freehold,1250,...,0,0,0,0,0,0,0,0,0,1
3,3,2500000,6034,530,NaN,NaN,1,1,NaN,1250,...,0,0,0,0,0,0,0,0,0,1
4,4,16000000,18824,635,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,2,Co-operative Society,1250,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,6300000,3225,1000,Garden/Park,Bollywood Esencia,3,3,Freehold,1953,...,0,0,0,0,0,0,0,0,0,0
187527,187527,5500000,3274,1000,"Garden/Park, Main Road",Sushma Urban Views,3,2,NaN,1680,...,0,1,0,0,0,0,0,0,0,1
187528,187528,7600000,4343,1250,"Garden/Park, Main Road",Bollywood Esencia,3,2,Freehold,1250,...,0,0,0,0,0,0,0,0,0,1
187529,187529,3000000,4231,1000,Main Road,Friends Enclave,2,2,NaN,709,...,0,0,0,0,0,0,0,0,0,1
187530,187530,11800000,6162,1000,"Garden/Park, Pool",Affinity Greens,4,4,Freehold,1915,...,0,1,0,0,0,0,0,0,0,1

In [169]:
df = df.drop(columns=["Index"])

In [170]:
df = df.drop(columns=["Price (in rupees)"])

In [171]:
df

,Amount(in rupees),Carpet Area,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,Car_Parking_Count,Car_Parking_Type,...,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West,Transaction_Other,Transaction_Rent/Lease,Transaction_Resale
0,4200000,500,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,1250,1,nan,...,0,0,0,0,0,0,0,0,0,1
1,9800000,473,Garden/Park,Dosti Vihar,2,2,Freehold,1250,1,open,...,0,0,0,0,0,0,0,0,0,1
2,14000000,779,Garden/Park,Sunrise by Kalpataru,2,2,Freehold,1250,1,covered,...,0,0,0,0,0,0,0,0,0,1
3,2500000,530,NaN,NaN,1,1,NaN,1250,1,nan,...,0,0,0,0,0,0,0,0,0,1
4,16000000,635,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,2,Co-operative Society,1250,1,covered,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,6300000,1000,Garden/Park,Bollywood Esencia,3,3,Freehold,1953,1,covered,...,0,0,0,0,0,0,0,0,0,0
187527,5500000,1000,"Garden/Park, Main Road",Sushma Urban Views,3,2,NaN,1680,1,covered,...,0,1,0,0,0,0,0,0,0,1
187528,7600000,1250,"Garden/Park, Main Road",Bollywood Esencia,3,2,Freehold,1250,1,covered,...,0,0,0,0,0,0,0,0,0,1
187529,3000000,1000,Main Road,Friends Enclave,2,2,NaN,709,1,nan,...,0,0,0,0,0,0,0,0,0,1
187530,11800000,1000,"Garden/Park, Pool",Affinity Greens,4,4,Freehold,1915,1,covered,...,0,1,0,0,0,0,0,0,0,1

In [172]:
# Ensure column is string
df['Floor'] = df['Floor'].astype(str)

# Extract BOTH numbers
df[['Current_Floor', 'Total_Floors']] = df['Floor'].str.extract(r'(\d+)\D+(\d+)')

# Convert to numeric
df[['Current_Floor', 'Total_Floors']] = df[['Current_Floor', 'Total_Floors']].astype(float)

KeyError: 'Floor'

In [173]:
from sklearn.model_selection import train_test_split

In [174]:
X = df.drop("Amount(in rupees)" , axis = 1)

In [175]:
y = df["Amount(in rupees)"]

In [176]:
X.shape

(187531, 101)

In [177]:
X

,Carpet Area,overlooking,Society,Bathroom,Balcony,Ownership,Super Area,Car_Parking_Count,Car_Parking_Type,location_ahmadnagar,...,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West,Transaction_Other,Transaction_Rent/Lease,Transaction_Resale
0,500,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,1250,1,nan,0,...,0,0,0,0,0,0,0,0,0,1
1,473,Garden/Park,Dosti Vihar,2,2,Freehold,1250,1,open,0,...,0,0,0,0,0,0,0,0,0,1
2,779,Garden/Park,Sunrise by Kalpataru,2,2,Freehold,1250,1,covered,0,...,0,0,0,0,0,0,0,0,0,1
3,530,NaN,NaN,1,1,NaN,1250,1,nan,0,...,0,0,0,0,0,0,0,0,0,1
4,635,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,2,Co-operative Society,1250,1,covered,0,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,1000,Garden/Park,Bollywood Esencia,3,3,Freehold,1953,1,covered,0,...,0,0,0,0,0,0,0,0,0,0
187527,1000,"Garden/Park, Main Road",Sushma Urban Views,3,2,NaN,1680,1,covered,0,...,0,1,0,0,0,0,0,0,0,1
187528,1250,"Garden/Park, Main Road",Bollywood Esencia,3,2,Freehold,1250,1,covered,0,...,0,0,0,0,0,0,0,0,0,1
187529,1000,Main Road,Friends Enclave,2,2,NaN,709,1,nan,0,...,0,0,0,0,0,0,0,0,0,1
187530,1000,"Garden/Park, Pool",Affinity Greens,4,4,Freehold,1915,1,covered,0,...,0,1,0,0,0,0,0,0,0,1

In [178]:
y.shape

(187531,)

In [179]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [180]:
# Train

In [181]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Garden/Park'